version: "2"

linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - wrapcheck
    - wsl
    - tagliatelle
    - ireturn
    - containedctx
    - gochecknoglobals
    - paralleltest
    - tparallel
    - revive
    - embeddedstructfieldcheck

  settings:
    govet:
      enable-all: true
    gocyclo:
      min-complexity: 10
    funlen:
      lines: 60
      statements: 30
    varnamelen:
      ignore-names:
        - t
        - b
        - m
        - tt
        - ctx
        - err
        - id
        - fn

run:
  timeout: 10m
  go: '1.25'
  tests: true
